# Generated by Django 6.0.6 on 2026-06-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_projectmember_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Владелец'), ('ADMIN', 'Админ'), ('MEMBER', 'Участник')], default='MEMBER', max_length=20),
        ),
    ]
